name: Run On Push to Master
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Create Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build jar
        run: mvn --batch-mode install verify -X -U
      - name: copy jar
        run: |
          cp target/bluewave-1.0.0.jar bluewave.jar
          cp -r target/lib lib
      - name: Archive distribution
        uses: actions/upload-artifact@v2
        with:
          name: distribution
          path: |
            bluewave.jar
            lib
            web
            models
            config.json