name: Run on every push

on: [push]


jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--aosp --dry-run"
          # Recommended if you use MacOS:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
  maven-sonar:
    name: SonarCloud Maven Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Perform Analysis
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=lmohseni-smc_BlueWave \
            -Dsonar.organization=lmohseni-smc \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.sources=src/main/,web/ \
            -Dsonar.exclusions=src/test/**/*,web/lib/**/*,web/data/**/*
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    name: Gradle Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        run: ./gradlew build
